name: balena

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: true
      matrix:
        fleet: [gh_klutchell/pi-hole, klutchell_apps/pi-hole]

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: balena-io/deploy-to-balena-action@637a7fa50308bc762ec8cda1f7aff381f6670657 # v2.0.110
        with:
          balena_token: ${{ secrets.BALENA_API_KEY }}
          fleet: ${{ matrix.fleet }}
